// Book rendering family — card, list row, and grid/list wrappers.
// Used together by every book listing page (Library, Missing, Upcoming,
// Hidden, Author Detail, Series detail). Kept in one file because BList
// only ever wraps BListRow and BGrid only ever wraps BCard.
import { useTheme } from "../theme";
import { fmtDate } from "../lib/format";

export function BCard({book,onAction,onClick,showAuthor,highlightAuthorId,showMamLink,selMode,selected,onToggleSel}){const t=useTheme();const isUp=!!book.is_unreleased;const hasCover=book.cover_url||book.cover_path;const isOtherAuthor=highlightAuthorId&&book.author_id&&book.author_id!==highlightAuthorId;
const handleClick=()=>{if(selMode){onToggleSel&&onToggleSel(book.id)}else{onClick&&onClick(book)}};
return<div onClick={handleClick} style={{minWidth:160,maxWidth:200,flex:"1 1 160px",background:selMode&&selected?t.accent+"15":t.bg2,border:`1px solid ${selMode&&selected?t.accent:isUp?t.cyan+"66":t.border}`,borderRadius:10,overflow:"hidden",cursor:"pointer",transition:"border-color 0.2s, background 0.15s",position:"relative",opacity:isOtherAuthor?0.55:1}}>{isUp?<span style={{position:"absolute",top:6,left:6,fontSize:9,fontWeight:700,background:t.cyan,color:"#fff",padding:"2px 6px",borderRadius:4,zIndex:2}}>UPCOMING</span>:null}{book.is_new?<span style={{position:"absolute",top:6,right:6,fontSize:9,fontWeight:700,background:t.red,color:"#fff",padding:"2px 6px",borderRadius:4,zIndex:2}}>NEW</span>:null}{book.owned===1&&!book.is_new?<span style={{position:"absolute",top:6,right:6,fontSize:9,fontWeight:600,background:t.grn,color:"#fff",padding:"2px 6px",borderRadius:4,zIndex:2}}>OWNED</span>:null}
<div style={{height:200,background:t.bg3,display:"flex",alignItems:"center",justifyContent:"center",overflow:"hidden",opacity:isUp?0.7:1}}>{hasCover?<img src={book.cover_url||`/api/covers/${book.id}`} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}} onError={e=>{e.target.style.display="none";e.target.nextSibling.style.display="flex"}}/>:null}<div style={{display:hasCover?"none":"flex",flexDirection:"column",alignItems:"center",gap:4,color:t.tg,fontSize:12,textAlign:"center",padding:12}}><span style={{fontSize:28}}>?</span><span>{book.title}</span></div></div>
<div style={{padding:"8px 10px"}}><div style={{fontSize:13,fontWeight:600,color:t.text2,lineHeight:1.3,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{book.title}</div>{book.series_name&&book.series_index?<div style={{fontSize:10,color:t.purt,marginTop:1}}>#{book.series_index}{book.series_total?` of ${book.series_total}`:""}</div>:null}{showAuthor&&book.author_name?<div style={{fontSize:11,color:isOtherAuthor?t.ylwt:t.td,marginTop:2}}>{book.author_name}</div>:null}{isUp&&book.expected_date?<div style={{fontSize:11,color:t.cyant,marginTop:2}}>Expected: {fmtDate(book.expected_date)}</div>:null}{showMamLink&&book.mam_url?<a href={book.mam_url} target="_blank" rel="noopener noreferrer" onClick={e=>e.stopPropagation()} style={{display:"inline-flex",alignItems:"center",gap:3,marginTop:3,fontSize:10,fontWeight:600,color:book.mam_status==="found"?t.grnt:t.ylwt,textDecoration:"none",padding:"2px 6px",borderRadius:4,background:book.mam_status==="found"?"#1a3a1a":"#3a3a1a",border:`1px solid ${book.mam_status==="found"?"#2a882a33":"#88882a33"}`}}>MAM ↗</a>:null}</div></div>}

export function BListRow({book,onAction,onClick,showAuthor,highlightAuthorId,showMamLink,selMode,selected,onToggleSel}){const t=useTheme();const isOtherAuthor=highlightAuthorId&&book.author_id&&book.author_id!==highlightAuthorId;const handleClick=()=>{if(selMode){onToggleSel&&onToggleSel(book.id)}else{onClick&&onClick(book)}};return<tr onClick={handleClick} style={{cursor:"pointer",borderBottom:`1px solid ${t.borderL}`,opacity:isOtherAuthor?0.55:1,background:selMode&&selected?t.accent+"15":"transparent"}}><td style={{padding:"8px 12px",fontSize:13,color:t.text2}}>{book.title}{book.is_new?<span style={{marginLeft:8,fontSize:9,fontWeight:700,background:t.red,color:"#fff",padding:"1px 5px",borderRadius:3}}>NEW</span>:null}{book.is_unreleased?<span style={{marginLeft:8,fontSize:9,fontWeight:700,background:t.cyan,color:"#fff",padding:"1px 5px",borderRadius:3}}>UPCOMING</span>:null}</td>{showAuthor?<td style={{padding:"8px 12px",fontSize:13,color:isOtherAuthor?t.ylwt:t.td}}>{book.author_name}</td>:null}<td style={{padding:"8px 12px",fontSize:13,color:t.td}}>{book.series_name?`${book.series_name}${book.series_index?` #${book.series_index}`:""}${book.series_total?` (${book.series_total})`:""}`:"—"}</td><td style={{padding:"8px 12px",fontSize:13,color:book.pub_date?t.td:book.expected_date?t.cyant:t.tg}}>{book.pub_date?fmtDate(book.pub_date):book.expected_date?fmtDate(book.expected_date):"Unknown"}</td><td style={{padding:"8px 12px",fontSize:11,color:t.tg}}>{book.source||"—"}</td>{showMamLink?<td style={{padding:"8px 12px"}}>{book.mam_url?<a href={book.mam_url} target="_blank" rel="noopener noreferrer" onClick={e=>e.stopPropagation()} style={{fontSize:11,fontWeight:600,color:book.mam_status==="found"?t.grnt:t.ylwt,textDecoration:"none",padding:"2px 8px",borderRadius:4,background:book.mam_status==="found"?"#1a3a1a":"#3a3a1a",border:`1px solid ${book.mam_status==="found"?"#2a882a33":"#88882a33"}`}}>MAM ↗</a>:<span style={{fontSize:11,color:t.tg}}>—</span>}</td>:null}</tr>}

export function BGrid({books,onAction,onBookClick,showAuthor,highlightAuthorId,showMamLink,selMode,sel,onToggleSel}){return<div className="book-grid" style={{display:"flex",flexWrap:"wrap",gap:12,alignItems:"start"}}>{books.map(b=><BCard key={b.id} book={b} onAction={onAction} onClick={onBookClick} showAuthor={showAuthor} highlightAuthorId={highlightAuthorId} showMamLink={showMamLink} selMode={selMode} selected={sel&&sel.has(b.id)} onToggleSel={onToggleSel}/>)}</div>}

export function BList({books,onAction,onBookClick,showAuthor=false,highlightAuthorId,showMamLink,selMode,sel,onToggleSel}){const t=useTheme();return<table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`2px solid ${t.border}`}}><th style={{padding:"8px 12px",textAlign:"left",fontSize:11,fontWeight:600,color:t.tg,textTransform:"uppercase"}}>Title</th>{showAuthor?<th style={{padding:"8px 12px",textAlign:"left",fontSize:11,fontWeight:600,color:t.tg,textTransform:"uppercase"}}>Author</th>:null}<th style={{padding:"8px 12px",textAlign:"left",fontSize:11,fontWeight:600,color:t.tg,textTransform:"uppercase"}}>Series</th><th style={{padding:"8px 12px",textAlign:"left",fontSize:11,fontWeight:600,color:t.tg,textTransform:"uppercase"}}>Date</th><th style={{padding:"8px 12px",textAlign:"left",fontSize:11,fontWeight:600,color:t.tg,textTransform:"uppercase"}}>Source</th>{showMamLink?<th style={{padding:"8px 12px",textAlign:"left",fontSize:11,fontWeight:600,color:t.tg,textTransform:"uppercase"}}>MAM</th>:null}</tr></thead><tbody>{books.map(b=><BListRow key={b.id} book={b} onAction={onAction} onClick={onBookClick} showAuthor={showAuthor} highlightAuthorId={highlightAuthorId} showMamLink={showMamLink} selMode={selMode} selected={sel&&sel.has(b.id)} onToggleSel={onToggleSel}/>)}</tbody></table>}
