import { useState, useEffect } from "react";
import { useTheme } from "../theme";
import { api } from "../api";
import { usePersist } from "../hooks/usePersist";
import { Btn } from "../components/Btn";
import { Load } from "../components/Load";
import { SearchBar } from "../components/SearchBar";
import { VT } from "../components/VT";
import { PB } from "../components/PB";

export default function AuthorsPage({onNav}){const t=useTheme();const[aus,setAus]=useState([]);const[ld,setLd]=useState(true);const[q,setQ]=usePersist("ap_q","");const[sort,setSort]=usePersist("ap_sort","name");const[vm,setVm]=usePersist("ap_vm","list");
const[selMode,setSelMode]=useState(false);const[sel,setSel]=useState(new Set());const[clearing,setClearing]=useState(false);const[scanning,setScanning]=useState(false);const[mamOn,setMamOn]=useState(false);
useEffect(()=>{api.get("/mam/status").then(r=>setMamOn(!!r.enabled)).catch(()=>{})},[]);
const toggleSel=id=>setSel(p=>{const n=new Set(p);if(n.has(id))n.delete(id);else n.add(id);return n});
const reload=()=>{setLd(true);api.get(`/authors?search=${q}&sort=${sort}`).then(d=>{setAus(d.authors||[]);setLd(false)})};
const clearData=async(type)=>{const labels={source:"source scan",mam:"MAM scan",both:"all scan"};if(!confirm(`Clear ${labels[type]} data for ${sel.size} author(s)? ${type==="source"||type==="both"?"This will DELETE all discovered (non-Calibre) books for these authors.":"MAM status will be reset and books will need re-scanning."}`))return;setClearing(true);try{await api.post("/authors/clear-scan-data",{author_ids:[...sel],clear_source:type==="source"||type==="both",clear_mam:type==="mam"||type==="both"});setSel(new Set());setSelMode(false);reload()}catch{alert("Error clearing data")}setClearing(false)};
const scanSources=async()=>{if(!confirm(`Run a source-plugin lookup for ${sel.size} author(s)? This may take a while.`))return;setScanning(true);window.dispatchEvent(new CustomEvent("athenascout:scan-started"));try{const r=await api.post("/authors/scan-sources",{author_ids:[...sel]});if(r.error){alert(`Scan failed: ${r.error}`)}else{alert(`Source scan complete: ${r.scanned} authors scanned, ${r.new_books} new books found`+(r.errors?`, ${r.errors} errors`:""));setSel(new Set());setSelMode(false);reload()}}catch(e){alert(`Scan failed: ${e.message||e}`)}setScanning(false);window.dispatchEvent(new CustomEvent("athenascout:scan-started"))};
const scanMam=async()=>{if(!confirm(`Run a MAM scan for un-scanned books across ${sel.size} author(s)? This may take a while.`))return;setScanning(true);try{const r=await api.post("/authors/scan-mam",{author_ids:[...sel]});if(r.error){alert(`MAM scan failed: ${r.error}`)}else{alert(`MAM scan complete: ${r.scanned||0} scanned, ${r.found||0} found, ${r.possible||0} possible, ${r.not_found||0} not on MAM`);setSel(new Set());setSelMode(false);reload()}}catch(e){alert(`MAM scan failed: ${e.message||e}`)}setScanning(false)};
useEffect(()=>{const c=new AbortController();setLd(true);api.get(`/authors?search=${encodeURIComponent(q)}&sort=${sort}`,c.signal).then(d=>{setAus(d.authors||[]);setLd(false)}).catch(e=>{if(!api.isAbort(e))setLd(false)});return()=>c.abort()},[q,sort]);
const AuthorCard=({a})=><div onClick={()=>selMode?toggleSel(a.id):onNav("author",a.id)} style={{minWidth:150,maxWidth:180,flex:"1 1 150px",background:selMode&&sel.has(a.id)?t.accent+"15":t.bg2,border:`1px solid ${selMode&&sel.has(a.id)?t.accent:t.borderL}`,borderRadius:10,padding:16,cursor:"pointer",display:"flex",flexDirection:"column",alignItems:"center",gap:8,textAlign:"center",transition:"background 0.15s, border-color 0.15s"}}>{a.image_url?<img src={a.image_url} alt="" style={{width:64,height:64,borderRadius:"50%",objectFit:"cover"}}/>:<div style={{width:64,height:64,borderRadius:"50%",background:t.bg4,display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,fontWeight:700,color:t.tg}}>{a.name?.charAt(0)}</div>}<div style={{fontSize:13,fontWeight:600,color:t.text2}}>{a.name}</div><div style={{display:"flex",gap:8,fontSize:11}}><span style={{color:t.grnt}}>{a.owned_count||0}</span><span style={{color:t.tg}}>/</span><span style={{color:t.ylwt}}>{a.missing_count||0}</span></div><div style={{width:"100%"}}><PB owned={a.owned_count||0} total={a.total_books||0}/></div></div>;
const AuthorRow=({a})=><div onClick={()=>selMode?toggleSel(a.id):onNav("author",a.id)} style={{display:"flex",alignItems:"center",gap:14,padding:"10px 14px",borderRadius:8,cursor:"pointer",background:selMode&&sel.has(a.id)?t.accent+"15":t.bg2,border:`1px solid ${selMode&&sel.has(a.id)?t.accent:t.borderL}`,transition:"background 0.15s, border-color 0.15s"}}>{a.image_url?<img src={a.image_url} alt="" style={{width:40,height:40,borderRadius:"50%",objectFit:"cover"}}/>:<div style={{width:40,height:40,borderRadius:"50%",background:t.bg4,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,fontWeight:700,color:t.tg}}>{a.name?.charAt(0)}</div>}<div style={{flex:1,minWidth:0}}><div style={{fontSize:14,fontWeight:600,color:t.text2}}>{a.name}</div><div style={{display:"flex",gap:12,fontSize:12,marginTop:2}}><span style={{color:t.grnt}}>{a.owned_count||0} owned</span><span style={{color:t.ylwt}}>{a.missing_count||0} missing</span><span style={{color:t.purt}}>{a.series_count||0} series</span></div></div><div style={{width:80}}><PB owned={a.owned_count||0} total={a.total_books||0}/></div></div>;
return<div style={{display:"flex",flexDirection:"column",gap:16}}>
<div className="bp-controls" style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:8,position:"sticky",top:56,zIndex:20,background:t.bg+"ee",backdropFilter:"blur(8px)",padding:"12px 0",marginTop:-12}}>
<h1 style={{fontSize:22,fontWeight:700,color:t.text,margin:0}}>Authors <span style={{fontSize:14,fontWeight:400,color:t.tg}}>({aus.length})</span></h1>
<div className="bp-right" style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><SearchBar value={q} onChange={setQ}/><select value={sort} onChange={e=>setSort(e.target.value)} style={{padding:"7px 10px",borderRadius:6,border:`1px solid ${t.border}`,background:t.inp,color:t.text2,fontSize:12}}><option value="name">Name</option><option value="books">Books</option><option value="missing">Missing</option></select><VT mode={vm} setMode={setVm}/><Btn size="sm" variant={selMode?"accent":"default"} onClick={()=>{setSelMode(!selMode);if(selMode)setSel(new Set())}}>{selMode?"Cancel Select":`Select`}</Btn></div></div>

{selMode&&sel.size>0?<div style={{display:"flex",alignItems:"center",gap:10,padding:"10px 14px",background:t.bg2,border:`1px solid ${t.border}`,borderRadius:8,flexWrap:"wrap"}}>
<span style={{fontSize:13,fontWeight:600,color:t.text2}}>{sel.size} author{sel.size>1?"s":""} selected</span>
<Btn size="sm" onClick={scanSources} disabled={scanning||clearing} style={{background:t.grn+"22",color:t.grnt,border:`1px solid ${t.grn}44`}}>{scanning?"…":""} Scan Sources</Btn>
{mamOn?<Btn size="sm" onClick={scanMam} disabled={scanning||clearing} style={{background:t.accent+"22",color:t.accent,border:`1px solid ${t.accent}44`}}>{scanning?"…":""} Scan MAM</Btn>:null}
<span style={{width:1,height:20,background:t.border,margin:"0 4px"}}/>
<Btn size="sm" onClick={()=>clearData("source")} disabled={clearing||scanning} style={{background:t.ylw+"22",color:t.ylwt,border:`1px solid ${t.ylw}44`}}>Clear Source Data</Btn>
{mamOn?<Btn size="sm" onClick={()=>clearData("mam")} disabled={clearing||scanning} style={{background:t.cyan+"22",color:t.cyant,border:`1px solid ${t.cyan}44`}}>Clear MAM Data</Btn>:null}
{mamOn?<Btn size="sm" onClick={()=>clearData("both")} disabled={clearing||scanning} style={{background:t.red+"22",color:t.redt,border:`1px solid ${t.red}44`}}>Clear Both</Btn>:null}
<Btn size="sm" onClick={()=>setSel(new Set())}>Deselect All</Btn>
</div>:null}
{ld?<Load/>:vm==="grid"?<div style={{display:"flex",flexWrap:"wrap",gap:12,alignItems:"start"}}>{aus.map(a=><AuthorCard key={a.id} a={a}/>)}</div>:<div style={{display:"flex",flexDirection:"column",gap:2}}>{aus.map(a=><AuthorRow key={a.id} a={a}/>)}</div>}
</div>}
